# Generated by Django 5.1.3 on 2024-11-15 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_alter_location_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=11.1111111, validators=[django.core.validators.RegexValidator(message="Latitude must be in the format like '44.5609447'.", regex='^-?\\d{1,2}\\.\\d+$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.FloatField(default=11.1111111, validators=[django.core.validators.RegexValidator(message="Longitude must be in the format like '44.5609447'.", regex='^-?\\d{1,3}\\.\\d+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type_sensor',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('wind_speed', 'Wind_speed')], max_length=20),
        ),
    ]
